### ISSUE TITLE
Tracking issue for compiler

### ISSUE THREAD

**Issue by cyderize** [shackle-rs/shackle#21]
- [ ] Spec for MicroZinc (Jip, 2022-08-26)
- [ ] Pretty printing of THIR as MiniZinc, running the test suite, etc. (Jason, 2022-09-02)
- [ ] Desugaring of var if-then-else, var comprehensions and rewriting into SSA
- [ ] Monomorphisation
- [ ] Decomposing optional types and records
- [ ] Totalisation
- [ ] Reification specialisation
- [ ] Removal of overloading
- [ ] Pretty printing of MIR

**Comment by Dekker1** [comment]
I probably did it the wrong way, but I manually made this tracking issue into a project: https://github.com/orgs/shackle-rs/projects/1

I think it probably is easier to just track it there and close this issue.
